### ISSUE TITLE
Examples not working with local backend

### ISSUE THREAD

**Issue by Nollde** [recast-hep/recast-atlas#118]
Dear experts,

I just wanted to try one of the great recast examples with a local workflow.
It appears that this is currently not possible out of the box.

The problem seems to be that `yadage` expects a `metadir` to create a `YadageSteering` object [here](https://github.com/yadage/yadage/blob/master/src/yadage/steering_object.py#L47-L66).
This metadir however is currently not set [here](https://github.com/recast-hep/recast-atlas/blob/HEAD/src/recastatlas/backends/local.py#L13-L23).

Please find a minimal example here:
```
(base) ➜  ~ conda create -n recast-tmp python
(base) ➜  ~ conda activate recast-tmp
(recast-tmp) ➜  ~ python -m pip install recast-atlas
(recast-tmp) ➜  ~ pip install yadage
(recast-tmp) ➜  ~ recast run examples/rome --backend local                     
2023-11-03 11:27:11,370 | packtivity.asyncback |   INFO | configured pool size to 10
2023-11-03 11:27:11,421 | recastatlas.subcomma |  ERROR | caught exception
Traceback (most recent call last):
  File "/Users/dnoll/anaconda3/envs/recast-tmp/lib/python3.12/site-packages/recastatlas/backends/local.py", line 21, in run_workflow
    run_workflow(**spec)
  File "/Users/dnoll/anaconda3/envs/recast-tmp/lib/python3.12/site-packages/yadage/steering_api.py", line 19, in run_workflow
    with steering_ctx(*args, **kwargs):
  File "/Users/dnoll/anaconda3/envs/recast-tmp/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/Users/dnoll/anaconda3/envs/recast-tmp/lib/python3.12/site-packages/yadage/steering_api.py", line 87, in steering_ctx
    ys = YadageSteering.create(
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dnoll/anaconda3/envs/recast-tmp/lib/python3.12/site-packages/yadage/steering_object.py", line 61, in create
    prepare_meta(
  File "/Users/dnoll/anaconda3/envs/recast-tmp/lib/python3.12/site-packages/yadage/utils.py", line 229, in prepare_meta
    if os.path.exists(metadir):
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

Is this the expected behavior?
Or am I missing something more fundamental?

Thank you for your comments!

**Comment by matthewfeickert** [comment]
I think this is another case of https://github.com/yadage/yadage/issues/116 that is getting hit, as

```
recast run examples/rome --backend docker
```

runs without errors.

<details>
<summary>Run output:</summary>

```console
$ recast run examples/rome --backend docker
2023-11-04 04:15:18,036 | packtivity.asyncback |   INFO | configured pool size to 16
2023-11-04 04:15:18,371 |      yadage.creators |   INFO | initializing workflow with initdata: {'did': 404958, 'dxaod_file': 'https://recastwww.web.cern.ch/recastwww/data/reana-recast-demo/mc15_13TeV.123456.cap_recast_demo_signal_one.root', 'xsec_in_pb': 0.00122} discover: True relative: True
2023-11-04 04:15:18,371 |    adage.pollingexec |   INFO | preparing adage coroutine.
2023-11-04 04:15:18,371 |                adage |   INFO | starting state loop.
2023-11-04 04:15:18,458 |     yadage.wflowview |   INFO | added </init:0|defined|unknown>
2023-11-04 04:15:19,438 |     yadage.wflowview |   INFO | added </eventselection:0|defined|unknown>
2023-11-04 04:15:20,710 |     yadage.wflowview |   INFO | added </statanalysis:0|defined|unknown>
2023-11-04 04:15:22,162 |    adage.pollingexec |   INFO | submitting nodes [</init:0|defined|known>]
2023-11-04 04:15:22,666 |       pack.init.step |   INFO | publishing data: <TypedLeafs: {'did': 404958, 'dxaod_file': 'https://recastwww.web.cern.ch/recastwww/data/reana-recast-demo/mc15_13TeV.123456.cap_recast_demo_signal_one.root', 'xsec_in_pb': 0.00122}>
2023-11-04 04:15:22,666 |                adage |   INFO | unsubmittable: 0 | submitted: 0 | successful: 0 | failed: 0 | total: 3 | open rules: 0 | applied rules: 3
2023-11-04 04:15:24,248 |           adage.node |   INFO | node ready </init:0|success|known>
2023-11-04 04:15:24,248 |    adage.pollingexec |   INFO | submitting nodes [</eventselection:0|defined|known>]
2023-11-04 04:15:24,250 | pack.eventselection. |   INFO | starting file logging for topic: step
2023-11-04 04:15:36,945 |           adage.node |   INFO | node ready </eventselection:0|success|known>
2023-11-04 04:15:36,945 |    adage.pollingexec |   INFO | submitting nodes [</statanalysis:0|defined|known>]
2023-11-04 04:15:36,947 | pack.statanalysis.st |   INFO | starting file logging for topic: step
2023-11-04 04:15:42,039 |           adage.node |   INFO | node ready </statanalysis:0|success|known>
2023-11-04 04:15:42,059 | adage.controllerutil |   INFO | no nodes can be run anymore and no rules are applicable
2023-11-04 04:15:42,059 | adage.controllerutil |   INFO | no nodes can be run anymore and no rules are applicable
2023-11-04 04:15:42,060 |                adage |   INFO | unsubmittable: 0 | submitted: 0 | successful: 3 | failed: 0 | total: 3 | open rules: 0 | applied rules: 3
2023-11-04 04:15:45,620 |                adage |   INFO | adage state loop done.
2023-11-04 04:15:45,620 |                adage |   INFO | execution valid. (in terms of execution order)
2023-11-04 04:15:45,620 |                adage |   INFO | workflow completed successfully.
2023-11-04 04:15:45,620 |  yadage.steering_api |   INFO | done. dumping workflow to disk.
2023-11-04 04:15:45,622 |  yadage.steering_api |   INFO | visualizing workflow.
2023-11-03 23:15:46,306 | recastatlas.subcomma |   INFO | RECAST run finished.

RECAST result examples/rome recast-c2b6ce7a:
--------------
- name: CLs 95% based upper limit on poi
  value:
    exp: 0.8924846399964371
    exp_m1: 0.6377501820447065
    exp_m2: 0.4731739008380644
    exp_p1: 1.2720762961732819
    exp_p2: 1.7545752712294322
    obs: 1.3352971254860764
- name: CLs 95% at nominal poi
  value:
    exp: 0.25999040745937085
    exp_m1: 0.10547655600578199
    exp_m2: 0.03889040527686523
    exp_p1: 0.5345040672498215
    exp_p2: 0.8276574946063575
    obs: 0.574709475331039

```

</details>

which means that some dependencies have a bug that needs to get fixed. This isn't getting caught properly in our CI at the moment, so this will probably take some debugging early next week.

**Comment by matthewfeickert** [comment]
Ah, @Nollde no this is actually a simple permissions issue and lack of documentation at the end of it, in addition to https://github.com/yadage/yadage/issues/116. I should have debugged better.

Okay, starting from scratch in a Python 3.11 environment as I can't claim that Python 3.12 will have support for all dependencies yet.

```console
$ mkdir -p /tmp/debug && cd /tmp/debug
$ python -m venv recast-atlas-issue-118 && . recast-atlas-issue-118/bin/activate
(recast-atlas-issue-118) $ python -m pip install --upgrade pip setuptools wheel
(recast-atlas-issue-118) $ python -m pip install 'recast-atlas[local]' 'yadage<0.21.0'  # c.f. https://github.com/yadage/yadage/issues/116
```

If we then run

```
recast run examples/rome --backend local --tag debug
```

the jobs will start but then crash. That's strange as we already saw that running with the `docker` backend works fine. If we investiage the log files by checking out `recast-debug/eventselection/_packtivity/eventselection.run.log`, we'll see that we get a permissions error

```
...
2023-11-04 01:14:50,653 | pack.eventselection. |   INFO | b'/build2/atnight/localbuilds/nightlies/21.2/AnalysisBase/athena/PhysicsAnalysis/D3PDTools/EventLoop/Root/Driver.cxx:107:exception: could not create output directory /tmp/debug/recast-debug/eventselection/submitDir'
...
```

that seems strange until we remember that `recast-atlas` currently assumes that you're `root` for all operations and so if you're not then you're going to need to tell it that you want it to run the containers as `root`. If you run

```
recast run examples/rome --backend docker --tag debug-helper
```

then we see that all the `docker run` commands have `-u root` added into them

```console
$ grep "docker run" recast-debug-helper/eventselection/_packtivity/eventselection.step.log
docker run --rm -i  --cidfile /tmp/debug/recast-debug-helper/eventselection/_packtivity/eventselection.cid    -u root  -v /tmp/debug/recast-debug-helper/eventselection:/tmp/debug/recast-debug-helper/eventselection:rw -v /tmp/debug/recast-debug-helper/init:/tmp/debug/recast-debug-helper/init:rw docker.io/reanahub/reana-demo-atlas-recast-eventselection:1.0 sh -c bash
2023-11-04 06:20:29,219 | pack.eventselection. |  DEBUG | moving on from subprocess execution: docker run --rm -i  --cidfile /tmp/debug/recast-debug-helper/eventselection/_packtivity/eventselection.cid    -u root  -v /tmp/debug/recast-debug-helper/eventselection:/tmp/debug/recast-debug-helper/eventselection:rw -v /tmp/debug/recast-debug-helper/init:/tmp/debug/recast-debug-helper/init:rw docker.io/reanahub/reana-demo-atlas-recast-eventselection:1.0 sh -c bash
2023-11-04 06:20:29,219 | pack.eventselection. |  DEBUG | finally for docker run --rm -i  --cidfile /tmp/debug/recast-debug-helper/eventselection/_packtivity/eventselection.cid    -u root  -v /tmp/debug/recast-debug-helper/eventselection:/tmp/debug/recast-debug-helper/eventselection:rw -v /tmp/debug/recast-debug-helper/init:/tmp/debug/recast-debug-helper/init:rw docker.io/reanahub/reana-demo-atlas-recast-eventselection:1.0 sh -c bash
```

as a result of this `packtivity` environment setting getting set in the `recast-atlas` Dockerfile

https://github.com/recast-hep/recast-atlas/blob/b660442ff2654db8d9bf9efe79eff4894eb6bf02/docker/Dockerfile#L49

(this isn't documented well).

With that in mind we just need to do the same locally with our `local` backend run

```
PACKTIVITY_DOCKER_CMD_MOD="-u root" recast run examples/rome --backend local --tag working
```

then things run as expected.

So:
* There is still a bug with https://github.com/yadage/yadage/issues/116
* Running with the `local` backend requires the `'local'` extra and using it isn't documented well.
* `packtivity` environmental options aren't documented well at all either.

**Comment by matthewfeickert** [comment]
> If you are interested we could troubleshoot why you need the `PACKTIVITY_DOCKER_CMD_MOD` and I don't.
> But we do not necessarily need to do this and I am also happy to just leave things as they are.

That might be interesting, but I suspect that this would be related to id groups on our local machines. I'll open up an Issue though for the future as having as unified of an experience is beneficial in the long run. :+1: 

Though the first order of priority when I get time to do recast development again is fixing https://github.com/yadage/yadage/issues/116 and then getting that tested with the REANA team.
