### ISSUE TITLE
eval "$(recast auth reana-setup)" fails

### ISSUE THREAD

**Issue by lukasheinrich** [recast-hep/recast-atlas#72]
on a fresh venv installing `recast-atlas[reana]`:

`reana-client secrets-add --help` seems too fail due to 

```
Traceback (most recent call last):
  File "/private/tmp/test_reana/_venv/bin/reana-client", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/private/tmp/test_reana/_venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3126, in <module>
    @_call_aside
  File "/private/tmp/test_reana/_venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3110, in _call_aside
    f(*args, **kwargs)
  File "/private/tmp/test_reana/_venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3139, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/private/tmp/test_reana/_venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/private/tmp/test_reana/_venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 898, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/private/tmp/test_reana/_venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 784, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'isoduration; extra == "format"' distribution was not found and is required by jsonschema
```

has something recently changed @matthewfeickert ?

**Comment by matthewfeickert** [comment]
Closing as this should definitely be resolved with release of [`recast-atlas` `v0.1.9`](https://github.com/recast-hep/recast-atlas/releases/tag/v0.1.9).
